import sharp from 'sharp';
import { createHash } from 'node:crypto';
import { mkdir, writeFile, readdir, unlink } from 'node:fs/promises';

// Keep source artwork; generate padded 2x tiles for crisp phone displays.
const types = ['root', 'bigchest', 'boss', 'chest', 'chiyou', 'fruit', 'hack', 'idk',
  'miniboss', 'poison', 'shanhai', 'yi', 'cpu', 'collectible', 'data', 'herb', 'vial',
  'robot', 'jade', 'keyitem', 'artifact', 'darksteel'];
const cell = 88;
const columns = 6;
const width = cell * columns;
const height = cell * Math.ceil(types.length / columns);
try {
  const images = await Promise.all(types.map(async (type, index) => ({
    input: await sharp(`public/icons/${type}.png`).resize(80, 80, {fit:'fill'}).png().toBuffer(),
    left: (index % columns) * cell + 4, top: Math.floor(index / columns) * cell + 4,
  })));
  const sprite = await sharp({create:{width,height,channels:4,background:'#00000000'}})
    .composite(images).png().toBuffer();
  const filename = `markers-${createHash('sha256').update(sprite).digest('hex').slice(0,16)}.png`;
  await mkdir('public/sprites', {recursive:true});
  await writeFile(`public/sprites/${filename}`,sprite);
  const css = [`/* Generated by scripts/generate-sprite.mjs. */`,
    `.marker-art { display:block; width:40px; height:40px; background-image:url('/sprites/${filename}'); background-size:${width/2}px ${height/2}px; }`];
  types.forEach((type,index)=>css.push(`.marker-art-${type} { background-position:-${((index%columns)*cell+4)/2}px -${(Math.floor(index/columns)*cell+4)/2}px; }`));
  await writeFile('app/sprites.css',css.join('\n')+'\n');
  for (const old of await readdir('public/sprites')) {
    if (/^markers-[a-f0-9]+\.png$/.test(old) && old !== filename) await unlink(`public/sprites/${old}`);
  }
  console.log(`${filename}: ${sprite.length} bytes for ${types.length} icons`);
} catch (error) {
  console.error('Could not generate icon sprite:',error);
  process.exitCode = 1;
}
